image: node:latest

stages:
  - deploy

deploy:dev:
  stage: deploy
  script:
    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    - apt-get update && apt-get install -qyf python-dev
    - curl -O https://bootstrap.pypa.io/pip/2.7/get-pip.py
    - python get-pip.py
    - pip install awscli
    - npm install -g @angular/cli@8
    - npm install
    - export NODE_OPTIONS=--openssl-legacy-provider
    - ng build --configuration=dev
    - aws s3 sync --delete ./dist/fuse/ s3://onlyborrow-admin-uk-dev/
    - aws cloudfront create-invalidation --distribution-id EHRFTEX2NICIM --path /index.html

  only:
    - development

deploy:testing:
  stage: deploy
  script:
    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    - apt-get update && apt-get install -qyf python-dev
    - curl -O https://bootstrap.pypa.io/pip/2.7/get-pip.py
    - python get-pip.py
    - pip install awscli
    - npm install -g @angular/cli@8
    - npm install
    - export NODE_OPTIONS=--openssl-legacy-provider
    - ng build --configuration=testing
    - aws s3 sync --delete ./dist/fuse/ s3://onlyborrow-admin-uk-testing/
    - aws cloudfront create-invalidation --distribution-id E1YZZ3ENMEDKIS --path /index.html

  only:
    - testing

deploy:production:
    stage: deploy
    script:
        - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
        - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
        - apt-get update && apt-get install -qyf python-dev
        - curl -O https://bootstrap.pypa.io/pip/2.7/get-pip.py
        - python get-pip.py
        - pip install awscli
        - npm install -g @angular/cli@8
        - npm install
        - export NODE_OPTIONS=--openssl-legacy-provider
        - ng build --configuration=production
        - aws s3 sync --delete ./dist/fuse/ s3://onlyborrow-admin-uk-prod/
        - aws cloudfront create-invalidation --distribution-id E2AB01MS27OEX2 --path /index.html

    only:
        - master